# Generated by Django 4.1.2 on 2024-02-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='defaults/background.jpg', upload_to='backgrounds/'),
        ),
    ]
