# Generated by Django 4.1.2 on 2024-02-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
