# Generated by Django 4.1.2 on 2024-02-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
