# Generated by Django 4.1.2 on 2024-02-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_comment_options_remove_comment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='participant',
            new_name='user',
        ),
    ]
