# Generated by Django 4.1.2 on 2024-02-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ordering_filter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
