# Generated by Django 4.1.2 on 2024-02-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_event_ordering_filter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['ordering_filter']},
        ),
        migrations.AlterField(
            model_name='event',
            name='ordering_filter',
            field=models.IntegerField(unique=True),
        ),
    ]
