# Generated by Django 4.1.2 on 2024-02-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_eventregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregistration',
            old_name='participant',
            new_name='teamleader',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='submitted_names',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='submitted_name_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='submitted_name_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='submitted_name_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='submitted_name_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='submitted_name_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
