# Generated by Django 4.1.2 on 2024-02-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_submitted_name_1_eventregistration_memeber_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='payment',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
