# Generated by Django 4.1.2 on 2024-02-28 02:32

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_eventregistration_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='payment',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.participant_event_directory_path),
        ),
    ]
