# Generated by Django 4.1.2 on 2024-02-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_eventregistration_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='members_required',
            new_name='max_members',
        ),
        migrations.AddField(
            model_name='event',
            name='min_members',
            field=models.IntegerField(null=True),
        ),
    ]
