# Generated by Django 4.1.2 on 2024-02-28 07:59

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_members_required_event_max_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='QR_code',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.qr_upload_to),
        ),
    ]
