# Generated by Django 4.1.2 on 2024-03-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_event_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
